### ISSUE TITLE
Create Route - Meta Description page

### ISSUE THREAD

**Issue by BertoCruz** [BertoCruz/Meta-Music#2]
## Functionality
- [ ] As a user, when my artist search is submitted, I should see a container holding an artists' music meta information
- [ ] As a User, I should see a picture of the artist[s]
- [ ] As a User, I should see the meta description to the left of the picture
- [ ] As a User, I should be able to click on the "Meta-Music" header to go back to the landing page
- [ ] As a User, I should see a search box on the header navbar and I should be able to do a new search from here
